phone_sensors_bridge_server:
  ros__parameters:
    host: "0.0.0.0"
    port: 2000
    debug: false
    secret_key: "secret!"
    ssl_certificate: "certs/certificate.crt"
    ssl_private_key: "certs/private.key"
    use_ros_time: false
    time_reference_source_device: "ros_to_device"
    frame_id_imu: "base_link"
    frame_id_gnss: "base_link"
    frame_id_image: "base_link"
    time_reference_source_gnss: "device_to_gnss"
    time_reference_frequency: -1.0
    imu_frequency: 50.0
    gnss_frequency: 10.0
    camera_device_label: "camera2 1, facing front"
    video_fps: 20.0
    video_width: 1280
    video_height: 720
    video_compression: 0.3
