# These server parameters are used to visualize the phone sensors in RViz.
phone_sensors_bridge_server:
  ros__parameters:
    host: "0.0.0.0"
    port: 2000
    debug: false
    secret_key: "secret!"
    ssl_certificate: "certs/certificate.crt"
    ssl_private_key: "certs/private.key"
    use_ros_time: false
    time_reference_source_device: "ros_to_device"
    time_reference_source_gnss: "device_to_gnss"
    time_reference_frequency: -1.0
    imu_frequency: 50.0
    gnss_watch_position: true
    frame_id_imu: "base_link"
    frame_id_gnss: "gnss"
    frame_id_image_camera1: "camera1"
    frame_id_image_camera2: "camera2"
    camera1_device_label: "camera 1, facing front"
    camera1_video_fps: 20.0
    camera1_video_width: 640
    camera1_video_height: 480
    camera1_video_compression: 0.3
    camera1_calibration_file: ""
    camera2_device_label: "camera 0, facing back"
    camera2_video_fps: 20.0
    camera2_video_width: 480
    camera2_video_height: 640
    camera2_video_compression: 0.3
    camera2_calibration_file: ""
    usb_enabled: false
    usb_device_type: "cdc"
    usb_baud": 115200
