name: Build packages
on: [push]
jobs:
  humble:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: phone_sensors
          target-ros2-distro: humble
          no-symlink-install: true
          skip-tests: true
  jazzy:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: phone_sensors
          target-ros2-distro: jazzy
          no-symlink-install: true
          skip-tests: true
  rolling:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: phone_sensors
          target-ros2-distro: rolling
          no-symlink-install: true
          skip-tests: true
