name: Build packages
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            distro: humble
          - os: ubuntu-24.04
            distro: jazzy
          - os: ubuntu-latest
            distro: rolling
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: phone_sensors_bridge
          target-ros2-distro: ${{ matrix.distro }}
          no-symlink-install: true
          skip-tests: true
